### ISSUE TITLE
Date fields don't match

### ISSUE THREAD

**Issue by Salvelop07** [WhityGhost/gh0ffice#2]
I used this module and it was very wonderful.
But some weird things I discovered.
Because created date and modified date is more recent than access date.
I understand created date could be more recent than modified date.
But it's impossible access date isn't the latest date field.

**Comment by WhityGhost** [comment]
It is already fixed in the latest version.

**Comment by Salvelop07** [comment]
Oh, yes, you're right.
Sorry for not being up-to-date.
